export const config = {
  runner: "local",
  hostname: "example.experitest.com",
  protocol: "https",
  port: 443,
  path: "/wd/hub",
  specs: ["./driver/fetch/get-calendar-data.js"],
  exclude: [],
  maxInstances: 10,
  capabilities: [
    {
      "experitest:accessKey": "EXPERITEST_ACCESS_KEY",
      maxInstances: 5,
      browserName: "chrome",
      acceptInsecureCerts: true,
    },
  ],
  logLevel: "info",
  outputDir: "./logs",
  bail: 0,
  baseUrl: "http://localhost",
  waitforTimeout: 10000,
  connectionRetryTimeout: 120000,
  connectionRetryCount: 3,
  services: ["chromedriver"],
  framework: "mocha",
  reporters: ["spec"],
  mochaOpts: {
    ui: "bdd",
    timeout: 60000,
  },
};
